version: '3.3'
services:
    bot:
        build: .
        image: botapp
        command: python main.py
        restart: unless-stopped
        tty: true
        networks:
            - app-network
        volumes:
          - ./persistence/:/usr/src/app/persistence/
          - bot-logs:/var/log/pitto/

#Docker Networks
networks:
    app-network:
        driver: bridge

volumes:
    bot-logs: